Feature/likes
wecode-bootcamp-korea/37-2nd-yourhouse-backend pull request #11
Opened 2022-10-12 09:48 UTC by JaeHoChoo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ 0] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 좋아요 create delete API 입니다

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 로그인 입력 데이터 유효성 검사 (예시 - 프론트)
- 입력창에 변화가 일어날 때 마다 유효성 검사 함수가 실행된다.
- 유효성 검사 함수의 반환값(boolean)에 따라 버튼의 배경색과 disabled 속성이 변화한다.
- 테스트 방법 : `/login` 페이지 이동 >>> 로그인 input 데이터 입력

2. 로그인 데이터 처리 (예시 - 백엔드)
- 조건문과 정규식을 이용한 email과 password 유효성 검사를 진행
- 유효섬 검사를 통과하지 못 할 경우 에러 메시지를 반환 예외 처리 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 사용자가 발생시킬 수 있는 다양한 예외 케이스에 대해 고민하게 되었습니다. (예시)
- 문자열 데이터 입력 시 마지막에 빈 문자열이 포함되어 있는 경우 데이터 처리가 올바르게 되지 않아 유효성 검사에 빈 문자열 제거하는 로직을 추가하였습니다. (예시)

<br />

## :: 기타 질문 및 특이 사항

2022-10-12 11:27 UTC, JaeHoChoo commented
콘플릭트 날거 수정해서 미리 리베이스해서 올렸습니다.

2022-10-12 11:54 UTC, JaeHoChoo commented
수정햇습니다

2022-10-13 01:59 UTC, lordmyshepherd requested changes

2022-10-13 01:59 UTC, lordmyshepherd commented on models/likeDao.js
> +    )
데이터를 지우거나 업데이트 하는 코드에서는 아래와 같이 삭제된 데이터가 
개발자가 예측한 수와 맞는지 반드시 확인해야 합니다.

```javascript
const deletePost = async (postId, userId) => {
	const deletedRows = (await dataSource.query(`
		DELETE FROM posts
		WHERE id=? AND user_id=?`, 
		[postId, userId]
	)).affectedRows

	if (deletedRows !== 0 && deletedRows !== 1) throw new Error('UNEXPECTED_NUMBER_OF_RECORDS_DELETED')
	
	return deletedRows
}

```

2022-10-13 03:15 UTC, JaeHoChoo commented
like Dao 단 에상 변화 수 고려 에러 핸들링 추가 및 콘플릭트 제거후 리베이스

2022-10-13 05:26 UTC, lordmyshepherd requested changes

2022-10-13 05:26 UTC, lordmyshepherd commented on models/likeDao.js
> +    if (addLikeLaws !==0 && addLikeLaws !==1) throw new Error('UNEXPECTED_NUMBER_OF_RECORDS_ADDED')
데이터를 INSERT 하는 경우에는 전체 record를 대상으로 하는 쿼리문이 아니기 때문에, INSERT 한 값을 비교할 필요가 없습니다~

2022-10-13 05:26 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-10-13 05:26 UTC, merged