[ADD]카카오 소셜 로그인/회원가입 구현
wecode-bootcamp-korea/37-2nd-yourhouse-backend pull request #4
Opened 2022-10-07 05:05 UTC by pienkk

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 카카오 API 를 이용한 로그인 / 회원가입 구현
<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 카카오 API를 이용한 로그인 / 회원가입 
- 프론트에서 인가 코드를 /users/auth 로 query parameter 로 전달 받으면 해당 코드를 이용해 토큰 발급/ 유저 정보 조회
- DB에서 회원 조회후 회원 존재하지 않을 경우 회원가입
- JWT 토큰 반환

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 함수형으로 구현했던 기능을 CLASS 문법과 promise 문법을 이용해 수정해 봄으로써 새로운 문법을 좀더 이해하게 되었습니다.

<br />

2022-10-07 06:24 UTC, Kang-kyunghun requested changes

2022-10-07 06:24 UTC, Kang-kyunghun commented on middleware/auth.js
> +const accessToken = async (req, res, next) => {
함수 이름은 명사형보다 해당 함수의 역할을 동사형으로 바꿔주시면 좋을 것 같습니다.

2022-10-07 06:24 UTC, Kang-kyunghun commented on models/userDao.js
> +}
social type이 있던 것으로 기억하는데, 타입까지 존재하게 되면 해당 소셜 타입에 맞는 소셜 아이디를 확인해 주어야 합니다.

2022-10-09 11:43 UTC, pienkk commented
유닛 테스트 완료 했습니다!

2022-10-10 02:13 UTC, merged