[ADD] 포스팅 댓글 기능
wecode-bootcamp-korea/37-2nd-yourhouse-backend pull request #6
Opened 2022-10-10 10:52 UTC by WJJayyy

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 포스팅 글에 댓글 추가 및 삭제기능

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
 - 포스팅 글에 댓글 기능 추가 및 삭제기능 추가

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)

<br />

## :: 기타 질문 및 특이 사항

2022-10-12 10:54 UTC, lordmyshepherd requested changes

2022-10-12 10:54 UTC, lordmyshepherd commented on controllers/commentController.js
> +    // const userId = req.user.id
auth middleware만 적용해서 다시 푸시해주세요~

2022-10-12 10:54 UTC, lordmyshepherd commented on controllers/commentController.js
> +    // const userId = req.user.id
전반적으로 코드는 깔끔합니다!

2022-10-12 13:46 UTC, WJJayyy commented on controllers/commentController.js
> +    // const userId = req.user.id
auth middleware만 적용해서 푸시 했습니다.
감사합니다!

2022-10-13 01:44 UTC, lordmyshepherd commented
LGTM 👍🏻

2022-10-13 01:44 UTC, merged